### ISSUE TITLE
Sensor not working

### ISSUE THREAD

**Issue by poudenes** [Juvawa/HomeAssistant9292OvApiSensor#7]
Hi ALl,

Home Assistant 0.110.4

Copied all the 3 files in the correct folder. Create his sensor:

```
###########################################################################################
# SENSOR dutch_public_transport_api
# https://github.com/Juvawa/HomeAssistant9292OvApiSensor
###########################################################################################
---
platform: dutch_public_transport_api
name: "Asdz - Utr"
station: station-amsterdam-zuid
destination: station-utrecht-centraal
show_future_departures: 4
```
Get this error after a while:

```
Logger: homeassistant.helpers.entity
Source: custom_components/dutch_public_transport_api/sensor.py:182 
First occurred: June 4, 2020, 6:40:44 PM (2 occurrences) 
Last logged: June 4, 2020, 9:50:29 PM

Update for sensor.asdz_utr fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dutch_public_transport_api/sensor.py", line 127, in update
    self._json_data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/dutch_public_transport_api/sensor.py", line 182, in update
    result = response.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

```
Logger: homeassistant.helpers.entity
Source: custom_components/dutch_public_transport_api/sensor.py:180 
First occurred: 12:00:56 AM (5 occurrences) 
Last logged: 12:01:00 AM

Update for sensor.asdz_utr fails
Update for sensor.asdz_utr_future_1 fails
Update for sensor.asdz_utr_future_2 fails
Update for sensor.asdz_utr_future_3 fails
Update for sensor.asdz_utr_future_4 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dutch_public_transport_api/sensor.py", line 127, in update
    self._json_data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/dutch_public_transport_api/sensor.py", line 180, in update
    headers=self._headers,
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

**Comment by metbril** [comment]
Have you already been able to fix the issue?
